### ISSUE TITLE
[FEATURE REQUEST] POST Unread Count to URL

### ISSUE THREAD

**Issue by rokk4** [famedly/hedwig#154]
## Feature Request: POST Unread Count to URL

As discussed with @nikzen:
We would like to request a feature enhancement for Hedwig to send unread count information to a specified backend endpoint.

### Description

To get rid of the matrix client running all the time in the background just to show the unread count, we need the capability to send the unread count information to our backend. Specifically, we need Hedwig to offer an option to set a URL (e.g., `http://api.example.com/update-unread`) where the following JSON payload will be sent:

```json
{
  "mxid": "${mxid}",
  "count": "${unread count}"
}
```

## Additional Requirements
- Configurable Endpoint URL: The URL to which the unread count information will be sent should be configurable.
- Bearer Token/API Key Support: The endpoint should support authentication through a Bearer token or API key to ensure secure communication.

**Comment by nikzen** [comment]
I will close it, as we will solve it different
